plugins {
    id "java"
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java {
            srcDirs += 'src/main'
            srcDirs += 'src/core'
        }
    }
}

dependencies {
    implementation 'org.apache.bcel:bcel:6.0'
    implementation 'mysql:mysql-connector-java:5.1.44'
    implementation 'org.xerial:sqlite-jdbc:3.32.3.2'

    implementation project(':microbat:sav.commons')
}
