source.. = src/main/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               icons/,\
               target/,\
               ddl/Location.sql,\
               ddl/MendingRecord.sql,\
               ddl/Regression.sql,\
               ddl/RegressionMatch.sql,\
               ddl/Step.sql,\
               ddl/StepVariableRelation.sql,\
               ddl/Trace.sql,\
src.excludes = src/test/
src.includes = icons/,\
               plugin.xml,\
               target/
